### ISSUE TITLE
c4 does not compile without further #include added

### ISSUE THREAD

**Issue by neosilky** [rswier/c4#21]
I just tried to compile using gcc 5.3.0 on x86_64 Arch Linux and it failed to compile, giving the following error:

```
c4.c: In function ‘main’:
c4.c:342:13: warning: implicit declaration of function ‘open’ [-Wimplicit-function-declaration]
   if ((fd = open(*argv, 0)) < 0) { printf("could not open(%s)\n", *argv); return -1; }
             ^
```

Command used was `gcc -m32 -o c4 c4.c`.

By adding `#include <fcntl.h>` as listed in the [open() man page](http://linux.die.net/man/3/open), it compiles and works fine.

Is this a correct fix and shall I send a pull request to do such an addition?

**Comment by rswier** [comment]
Yes, please do.  Thanks.

**Comment by neosilky** [comment]
Sent in #22.

**Comment by neosilky** [comment]
Thanks!
